

== Dictionary of Attributes for ICD Schema

The Attribute Dictionary defines attributes and includes references
to the events and objects in which they are used.

The following list reports the Attribute Name and Attribute Description,
along with their enumerations, in the form
`<"Attribute Name">:<"Attribute Description">`,
with sub-indexed enumerative items and corresponding
descriptions where applicable


=== {blank}

"AccessComplexity": "The access complexity Common Vulnerability Scoring
System (CVSS) metric.".

=== {blank}

"AccessList": "The list of requested access rights.".

=== {blank}

"AccessMask": "The access mask in a platform-native format.".

=== {blank}

"AccessCheckResult": "The list of access check results.".

=== {blank}

"Accessed": "The time that the file was last accessed.".

=== {blank}

"Accessor": "The name of the user who last accessed the object.".

=== {blank}

"AccountType": "The user account type (e.g. AWS. LDAP. Windows account.
etc.).".

=== {blank}

"AccountTypeID": "The user account type identifier (e.g. AWS. LDAP.
Windows account. etc.).".

==== {blank}

"Unknown": "The user account type is unknown.".

==== {blank}

"Other": "The user account type is not mapped.".

==== {blank}

"LDAPAccount"

==== {blank}

"WindowsAccount"

==== {blank}

"AWSIAMAccount"

==== {blank}

"GCPAccount"

==== {blank}

"AzureADAccount"

=== {blank}

"AccountUID": "The unique identifier of the account(e.g. AWS Account
ID).".

=== {blank}

"Activity": "The original activity that triggered the alert event.".

=== {blank}

"ActivityID": "The normalized identifier of the activity that triggered
the alert event.".

==== {blank}

"Unknown": "The event activity is unknown.".

==== {blank}

"Other": "The event activity is not mapped.".

=== {blank}

"ActorProcess": "The process that performed the operation or action
on the target object. For example. the process that could have created
a new file or violated a policy.".

=== {blank}

"ActualPermissions": "The permissions that were granted to the in
a platform-native format.".

=== {blank}

"AdditionalMalware": "This object describes additional malware reported
in a security finding".

=== {blank}

"AdditionalVulnerbailities": "This object describes additional vulnerabilities
reported in a security finding".

=== {blank}

"ClientTLSAlert": "The integer value of TLS alert if present. The
alerts are defined in the TLS specification in
<a target='_blank' href='https://datatracker.ietf.org/doc/html/rfc2246'>RFC-2246</a>.".

=== {blank}

"Algorithm": "The original hash algorithm. as reported by the event
source. which was used to create the digital fingerprint.".

=== {blank}

"AlgorithmID": "The identifier of the normalized hash algorithm. which
was used to create the digital fingerprint.".

==== {blank}

"Other"

==== {blank}

"Unknown"

==== {blank}

"MD5": "MD5 message-digest algorithm producing a 128-bit (16-byte)
hash value.".

==== {blank}

"SHA-1": "Secure Hash Algorithm 1 producing a 160-bit (20-byte) hash
value.".

==== {blank}

"SHA-256": "Secure Hash Algorithm 2 producing a 256-bit (32-byte)
hash value.".

==== {blank}

"SHA-512": "Secure Hash Algorithm 2 producing a 512-bit (64-byte)
hash value.".

==== {blank}

"CTPH": "The ssdeep generated fuzzy checksum. Also known as Context
Triggered Piecewise Hash (CTPH).".

=== {blank}

"DNSAnswer": "The Domain Name System (DNS) answers.".

=== {blank}

"APIdetails": "API object details information pertaining to the API
calls".

=== {blank}

"ApplicationName": "The name of the application that is associated
with the event or object.".

=== {blank}

"HTTPArguments": "The arguments sent along with the HTTP request.".

=== {blank}

"Assignee": "The name of the user who is assigned to the incident.".

=== {blank}

"AttackComplexity": "The conditions beyond the attacker's control
that must exist in order to exploit the vulnerability.".

=== {blank}

"AttackVectorID": "The attack vector Common Vulnerability Scoring
System (CVSS) metric.".

=== {blank}

"Attacks": "An array of attacks associated with an event.".

=== {blank}

"Attributes": "The bitmask value that represents the file attributes.".

=== {blank}

"AuthProtocol": "The authentication protocol as reported by the event
source.".

=== {blank}

"AuthProtocolID": "The authentication protocol used to create the
user session.".

==== {blank}

"Other"

==== {blank}

"Unknown"

==== {blank}

"NTLM"

==== {blank}

"Kerberos"

==== {blank}

"Digest"

==== {blank}

"OpenID"

==== {blank}

"SAML"

==== {blank}

"OAUTH2.0"

==== {blank}

"PAP"

==== {blank}

"CHAP"

==== {blank}

"EAP"

==== {blank}

"RADIUS"

=== {blank}

"AuthenticationID": "The authentication Common Vulnerability Scoring
System (CVSS) metric.".

=== {blank}

"AuthorizationInformation": "Authorization object provides details
related to Authorization".

=== {blank}

"AvailabilityImpactID": "The availability impact Common Vulnerability
Scoring System (CVSS) metric.".

=== {blank}

"BaseAddress": "The memory address where the module was loaded.".

=== {blank}

"BaseScore": "CVSS Base Score in the range of 0.0 to 10.0.".

=== {blank}

"BaseVector": "The base scoring vector for the CVSS score.".

=== {blank}

"OSBits": "The number of processor bits. For example: <code>64</code>
or <code>128</code>.".

=== {blank}

"OSBuild": "The operating system build number.".

=== {blank}

"TotalBytes": "The total number of bytes (in and out).".

=== {blank}

"BytesIn": "The number of bytes sent from the destination to the source.".

=== {blank}

"BytesOut": "The number of bytes sent from the source to the destination.".

=== {blank}

"Capabilities": "A list of RDP capabilities.".

=== {blank}

"Caption": "A short description or caption of the device. For example:
<code>Scanner 1</code> or <code>Database Manager</code>.".

=== {blank}

"Categories": "A list of categories.".

=== {blank}

"Category": "The original category of an event or object. as defined
by the event source. See specific usage.".

=== {blank}

"URLCategoryIDs": "An array of URL category identifies.".

==== {blank}

"Other": "The URL category is not mapped. See the <code>categories</code>
attribute. which may contain a data source specific value.".

=== {blank}

"CategoryID": "The category identifier of the event.".

=== {blank}

"CertificateChain": "The Chain of Certificate Serial Numbers field
provides a chain of Certificate Issuer Serial Numbers leading to the
Root Certificate Issuer.".

=== {blank}

"CertificateSerialNumber": "The Certificate Serial Number field provides
a short form. unique identifier for each Certificate generated by
a Certificate Issuer.".

=== {blank}

"CertificateUniqueIdentifier": "The unique identifier of the certificate
used to establish the TLS connection. For example. the AWS ARN of
the certificate.".

=== {blank}

"CipherSuite": "The negotiated cipher suite.".

=== {blank}

"CIS20List": "The CIS 20 is a list of 20 actions and practices an
organization’s security team can take on such that cyber attacks or
malware. are minimized and prevented.".

=== {blank}

"City": "The name of the city.".

=== {blank}

"Class": "The class name of the event or object.".

=== {blank}

"Class": "The class name of the event.".

=== {blank}

"ClassID": "The class identifier describes the attributes available
in an event. See specific usage.".

=== {blank}

"ClassificationIDs": "An array of malware classifications. Reference:
<a target='_blank' href='https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_oxlc4df65spl'>STIX Malware Types</a> ".

=== {blank}

"Classifications": "The malware classifications.".

=== {blank}

"Client": "The client object pertaining to the client/server exchange.".

=== {blank}

"ClientCipherSuites": "The client cipher suites that were exchanged
during the TLS handshake negotiation.".

=== {blank}

"Cloud": "The cloud where the event was originally created or logged.".

=== {blank}

"CloudPartition": "The canonical cloud partition name to which the
region is assigned (e.g. AWS Partitions: aws. aws-cn. aws-us-gov).".

=== {blank}

"CommandLine": "The full command line used to launch an application.
service. process. or job. For example: <code>ssh user@10.0.0.10</code>".

=== {blank}

"ResponseCode": "The numeric response sent to a HTTP request.".

=== {blank}

"ColorDepth": "The numeric color depth.".

=== {blank}

"Comment": "The user-provided comment.".

=== {blank}

"CompanyName": "The name of the company that published the file. For
example: <code>Microsoft Corporation</code>.".

=== {blank}

"Compliance": "The complaince object describes compliance related
details".

=== {blank}

"Component": "The name or relative pathname of a sub-component of
the data object. if applicable. </p>For example: <code>attachment.doc</code>.
<code>attachment.zip/bad.doc</code>. or <code>part.mime/part.cab/part.uue/part.doc</code>.".

=== {blank}

"Confidence": "The confidence of the reported finding as a percentage:
0%-100%.".

=== {blank}

"ConfidenceID": "The normalized confidence level refers to the accuracy
of the rule that created the finding. A rule with a low confidence
level means that the detection scope is wide and may create finding
reports that may not be malicious in nature.".

==== {blank}

"Other": "The confidence is not mapped to the defined enum values.
See the <code>confidence</code> attribute. which contains a data source
specific value.".

==== {blank}

"Unknown": "No confidence is assigned.".

==== {blank}

"Low"

==== {blank}

"Medium"

==== {blank}

"High"

=== {blank}

"Confidentiality": "The file content confidentiality.".

=== {blank}

"ConfidentialityID": "The file content confidentiality indicator.".

==== {blank}

"Other"

==== {blank}

"Unknown"

==== {blank}

"NotConfidential"

==== {blank}

"Confidential"

==== {blank}

"Secret"

==== {blank}

"TopSecret"

=== {blank}

"ConfidentialityImpact": "The confidentiality impact Common Vulnerability
Scoring System (CVSS) metric.".

=== {blank}

"ConnectionInfo": "The network connection information.".

=== {blank}

"ConnectionIdentifier": "The network connection identifier.".

=== {blank}

"Container": "The container information.".

=== {blank}

"HTTPContentType": "The request header that identifies the original
<a target='_blank' href='https://www.iana.org/assignments/media-types/media-types.xhtml'>media type </a> of the resource (prior to any content encoding applied for sending).".

=== {blank}

"Continent": "The name of the continent.".

=== {blank}

"Coordinates": "A two-element array. containing a longitude/latitude
pair. The format conforms with <a target='_blank' href='https://geojson.org'>GeoJSON</a>. For example: <code>[-73.983. 40.719]</code>.".

=== {blank}

"CorrelationUID": "The unique identifier used to correlate events.".

=== {blank}

"Count": "The number of times that events in the same logical group
occurred during the event <strong>Start Time</strong> to <strong>End
Time</strong> period.".

=== {blank}

"Country": "The ISO 3166-1 Alpha-2 country code. For the complete
list of country codes see <a target='_blank' href='https://www.iso.org/obp/ui/#iso:pub:PUB500001:en' >ISO 3166-1 alpha-2 codes</a>.<p><b>Note:</b> The two letter country code should be capitalized. For example: <code>US</code> or <code>CA</code>.</p>".

=== {blank}

"CreateMask": "The original Windows mask that is required to create
the object.".

=== {blank}

"CreationTime": "The time that the object was created. See specific
usage.".

=== {blank}

"Creator": "The user that created the object associated with event.
See specific usage.".

=== {blank}

"CreatorName": "The name of the user who created the incident.".

=== {blank}

"UserCredentialID": "The unique identifier of the user's credential.
For example. AWS Access Key ID.".

=== {blank}

"Criticality": "Criticality of a resource/object in question".

=== {blank}

"CustomerUID": "The unique customer identifier.".

=== {blank}

"CVEUIDs": "The common vulnerabilities and exposures (<a target='_blank'
href='https://cve.mitre.org/'>CVE</a>) unique identifiers.".

=== {blank}

"CVSSScores": "The CVSS object details Common Vulnerability Scoring
System (CVSS) scores from the advisory that are related to the vulnerability.".

=== {blank}

"Data": "The additional data that is associated with the event or
object. See specific usage.".

=== {blank}

"AuthorizationDecision/Outcome": "Decision/outcome of the authorization
mechanism (e.g. Approved. Denied)".

=== {blank}

"Description": "The description that pertains to the object or event.
See specific usage.".

=== {blank}

"DesktopDisplay": "The desktop display affiliated with the event".

=== {blank}

"Details": "Details of an entity. See specific usage".

=== {blank}

"DetectionStartTime": "The end time of a detection time period.".

=== {blank}

"DetectionStartTime": "The start time of a detection time period.".

=== {blank}

"DetectionUID": "The associated unique detection event identifier.
For example: detection response events include the <b>Detection ID</b>
of the original event.".

=== {blank}

"DeveloperUID": "The developer ID on the certificate that signed the
file.".

=== {blank}

"Device": "The device that reported the event.".

=== {blank}

"Direction": "The direction of the initiated connection. traffic.
or email.".

=== {blank}

"DirectionID": "The direction of the initiated connection. traffic.
or email.".

==== {blank}

"Unknown": "The direction is unknown.".

==== {blank}

"Inbound": "Inbound. from the Internet or outside network destined
for services on the inside network.".

==== {blank}

"Outbound": "Outbound. from inside the network destined for services
on the Internet or outside network.".

=== {blank}

"DNSUID": "The DNS packet identifier assigned by the program that
generated the query. The identifier is copied to the response.".

=== {blank}

"Domain": "The name of the domain.".

=== {blank}

"DestinationEndpoint": "The network destination endpoint.".

=== {blank}

"DestinationUser": "The user that was a target of an activity.".

=== {blank}

"Duration": "The event duration or aggregate time. the amount of time
the event covers from <code>start_time</code> to <code>end_time</code>
in milliseconds.".

=== {blank}

"OSEdition": "The operating system edition. For example: <code>Professional</code>.".

=== {blank}

"EmailAddress": "The user's email address.".

=== {blank}

"EndTime": "The end time of a time period. See specific usage.".

=== {blank}

"Enrichments": "The additional information from an external data source.
which is associated with the event. For example add location information
for the IP address in the DNS answers:</p><code>[{\"name\": \"answers.ip\".
\"value\": \"92.24.47.250\". \"type\": \"location\". \"data\": {\"city\":
\"Socotra\". \"continent\": \"Asia\". \"coordinates\": [-25.4153.
17.0743]. \"country\": \"YE\". \"desc\": \"Yemen\"}}]</code>".

=== {blank}

"Entity": "The managed entity that is being acted upon.".

=== {blank}

"EntityResult": "The updated managed entity.".

=== {blank}

"ErrorCode": "Error Code".

=== {blank}

"ErrorMessage": "Error Message".

=== {blank}

"EventName": "The event name. as defined by the event_uid.".

=== {blank}

"EventSource": "The event source from which the event originates.".

=== {blank}

"EventID": "The event ID identifies the event's semantics and structure.
The value is calculated by the logging system as: <code>class_id *
100 + activity_id</code>.".

=== {blank}

"ExitCode": "The exit code reported by a process when it terminates.
The convention is that zero indicates success and any non-zero exit
code indicates that some error occurred.".

=== {blank}

"ExpirationTime": "The expiration time. See specific usage.".

=== {blank}

"Port": "The IP port number exposed by container. For example 0.0.0.0:49155->
\<<exposed_port>>/tcp".

=== {blank}

"Facility": "The subsystem or application that is providing the event
data.".

=== {blank}

"FacilityDetail": "Additional detail about the source facility. For
example. details could include a the name of a particular application
instance (such as a database name) or a path to a monitored log file.".

=== {blank}

"FacilityUID": "The unique identifier of the facility.".

=== {blank}

"Feature": "The feature that reported the event.".

=== {blank}

"File": "The file that pertains to the event or object. See specific
usage.".

=== {blank}

"FileDiff": "File content differences used for change detection. For
example. a common use case is to identify itemized changes within
INI or configuration/property setting values.".

=== {blank}

"FileResult": "The result of the file change. It should contain the
new values of the changed attributes.".

=== {blank}

"Finding": "Finding object provides details related to a finding generated
by security tool".

=== {blank}

"Fingerprints": "An array of fingerprint objects associated with the
certificate.".

=== {blank}

"FirstOccurence": "Indicates when an entity is first observed.".

=== {blank}

"CommunicationFlagIDs": "The list of communication flag IDs.".

=== {blank}

"Flags": "The list of communication flags.".

=== {blank}

"Folder": "The folder that pertains to the event.".

=== {blank}

"FolderResult": "The result of the folder change. It should contain
the new values of the changed attributes.".

=== {blank}

"FullName": "The full name of a user.".

=== {blank}

"FunctionKeys": "The number of function keys on client keyboard.".

=== {blank}

"FunctionName": "The entry-point function of the module. The system
calls the entry-point function whenever a process or thread loads
or unloads the module.".

=== {blank}

"GatewayIPAddress": "The gateway IP address. For example: <code>10.0.0.1</code>.".

=== {blank}

"GatewayMACAddress": "The gateway media access control (MAC) address.".

=== {blank}

"Group": "The group object associated with an entity such as user.
policy. or rule.".

=== {blank}

"GroupName": "The name of the group that the resource belongs to.".

=== {blank}

"Groups": "The groups to which an entity belongs. See specific usage.".

=== {blank}

"HandshakeTime": "The amount of total time for the TLS handshake to
complete after the TCP connection is established. including client-side
delays. in milliseconds.".

=== {blank}

"Home": "The user's home folder.".

=== {blank}

"Hostname": "The hostname of an endpoint or a device.".

=== {blank}

"HTTPCookies": "The cookies object describes details about HTTP cookies".

=== {blank}

"HTTPHeaders": "Additional HTTP headers of an HTTP request or response.".

=== {blank}

"HTTPMethod": "The HTTP request method indicates the desired action
to be performed for a given resource. Expected values: <ul> <li>TRACE</li>
<li>CONNECT</li> <li>OPTIONS</li> <li>HEAD</li> <li>DELETE</li> <li>POST</li>
<li>PUT</li> <li>GET</li></ul>".

=== {blank}

"HTTPOnly": "A cookie attribute to make it inaccessible via JavaScript".

=== {blank}

"HTTPRequest": "The HTTP Request made to a web server.".

=== {blank}

"HTTPResponse": "The HTTP Response from a web server to a requester.".

=== {blank}

"HTTPStatus": "The Hypertext Transfer Protocol (HTTP) <a target='_blank'
href='https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml'>status code</a> returned to the client.".

=== {blank}

"HTTPVersion": "The Hypertext Transfer Protocol (HTTP) version.".

=== {blank}

"BIOSDate": "The BIOS date. For example: <code>03/31/16</code>.".

=== {blank}

"BIOSManufacturer": "The BIOS manufacturer. For example: <code>LENOVO</code>.".

=== {blank}

"SerialNumber": "The manufacturer serial number."

=== {blank}

"BIOSVersion": "The BIOS version. For example: <code>LENOVO G5ETA2WW
(2.62)</code>.".

=== {blank}

"ProcessorType": "The processor type. For example: <code>x86 Family
6 Model 37 Stepping 5</code>.".

=== {blank}

"Hypervisor": "The name of the hypervisor running on the device. For
example. <code>Xen</code>. <code>VMware</code>. <code>Hyper-V</code>.
<code>VirtualBox</code>. etc.".

=== {blank}

"IdentifierCookie": "The client identifier cookie during client/server
exchange.".

=== {blank}

"identity": "Identity Object details AuthN. AuthZ information pertaining
to the event".

=== {blank}

"IdentityProvider": "IDP object descivbes details pertaining to the
Identity Provider used".

=== {blank}

"Image": "The image used as a template to run a container or virtual
machine.".

=== {blank}

"IME": "The Input Method Editor (IME) file name.".

=== {blank}

"IMEI": "The International Mobile Station Equipment Identifier that
is associated with the device.".

=== {blank}

"InjectionType": "The process injection method.".

=== {blank}

"InjectionTypeID": "The normalized process injection type identifier.".

==== {blank}

"Other"

==== {blank}

"Unknown"

==== {blank}

"RemoteThread"

==== {blank}

"AccessibilityAPIs"

==== {blank}

"ProcessManipulationAPIs"

=== {blank}

"InstanceID": "The unique identifier of a VM instance.".

=== {blank}

"Integrity": "The process integrity (Windows only).".

=== {blank}

"IntegrityLevel": "The process integrity level (Windows only).".

=== {blank}

"IntegrityImpact": "The integrity impact Common Vulnerability Scoring
System (CVSS) metric.".

=== {blank}

"NetworkInterfaceID": "The unique identifier of the network interface.".

=== {blank}

"IntermediateIPAddresses": "The intermediate IP Addresses. For example.
the IP addresses in the HTTP X-Forwarded-For header.".

=== {blank}

"InternetConnection": "The internet connection type (e.g. modem. low_broadband.
satellite. high_broadband. wan. lan. autodetect).".

=== {blank}

"Invokedby": "The name of the service that made the request".

=== {blank}

"IPAddress": "The IP address. in either IPv4 or IPv6 format.".

=== {blank}

"CleartextCredentials": "Indicates whether the credentials were passed
in clear text.<p><b>Note:</b> True if the credentials were passed
in a clear text protocol such as FTP or TELNET. or if Windows detected
that a user's logon password was passed to the authentication package
in clear text.</p>".

=== {blank}

"CompliantDevice": "The event occurred on a compliant device.".

=== {blank}

"DefaultValue": "The indication of whether the value is from a default
value name. For example. the value name could be missing.".

=== {blank}

"ManagedDevice": "The event occurred on a managed device.".

=== {blank}

"OnPremises": "The indication of whether the location is on premises.".

=== {blank}

"PersonalDevice": "The event occurred on a personal device.".

=== {blank}

"Remote": "The indication of whether the session is remote.".

=== {blank}

"Renewal": "The indication of whether this is a lease/session renewal
event.".

=== {blank}

"System": "The indication of whether the object is part of the operating
system.".

=== {blank}

"TrustedDevice": "The event occurred on a trusted device.".

=== {blank}

"UserPresent": "The indication of whether the user was logged on at
event generation time.".

=== {blank}

"ISP": "The name of the Internet Service Provider (ISP).".

=== {blank}

"IssuerName": "The certificate issuer name.".

=== {blank}

"Job": "The job object that pertains to the event.".

=== {blank}

"KnowledgebaseArticles": "The KB article/s related to the entity".

=== {blank}

"Kernel": "The kernel resource object that pertains to the event.".

=== {blank}

"KeyLength": "The length of the encryption key.".

=== {blank}

"KeyboardLayout": "The keyboard locale identifier name (e.g.. en-US).".

=== {blank}

"KeyboardSubtype": "The keyboard numeric code.".

=== {blank}

"KeyboardType": "The keyboard type (e.g.. xt. ico).".

=== {blank}

"KillChainPhase": "The <a target='_blank' href='https://www.lockheedmartin.com/en-us/capabilities/cyber/cyber-kill-chain.html'>Cyber Kill Chain®</a> phase.".

=== {blank}

"KillChainPhaseID": "The <a target='_blank' href='https://www.lockheedmartin.com/en-us/capabilities/cyber/cyber-kill-chain.html'>Cyber Kill Chain®</a> phase identifier.".

==== {blank}

"Other"

==== {blank}

"Unknown": "The kill chain phase is unknown.".

==== {blank}

"Reconnaissance": "The attackers pick a target and perform a detailed
analysis. start collecting information (email addresses. conferences
information. etc.) and evaluate the victim’s vulnerabilities to determine
how to exploit them.".

==== {blank}

"Weaponization": "The attackers develop a malware weapon and aim to
exploit the discovered vulnerabilities.".

==== {blank}

"Delivery": "The intruders will use various tactics. such as phishing.
infected USB drives. etc.".

==== {blank}

"Exploitation": "The intruders start leveraging vulnerabilities to
executed code on the victim’s system.".

==== {blank}

"Installation": "The intruders install malware on the victim’s system.".

==== {blank}

"Command&Control": "Malware opens a command channel to enable the
intruders to remotely manipulate the victim's system.".

==== {blank}

"ActionsonObjectives": "With hands-on keyboard access. intruders accomplish
the mission’s goal.".

=== {blank}

"Labels": "The list of labels attached to an event. object. or attribute.".

=== {blank}

"Language": "The two letter lower case language codes. as defined
by <a target='_blank' href='https://en.wikipedia.org/wiki/ISO_639-1'>ISO
639-1</a>. For example: <code>en</code> (English). <code>de</code>
(German). or <code>fr</code> (French).".

=== {blank}

"LastOccurence": "Indicates when an entity was most recently observed.".

=== {blank}

"LastRun": "The last run time of application or service. See specific
usage.".

=== {blank}

"Latency": "TODO: The HTTP response latency. In seconds. milliseconds.
etc.?".

=== {blank}

"LeaseTime": "This represents the length of the DHCP lease in seconds.
This is present in DHCP Ack events. (activity_id = 1)".

=== {blank}

"ResponseLength": "The HTTP response length. in number of bytes.".

=== {blank}

"Lineage": "The lineage of the process.".

=== {blank}

"LoadType": "The load type describes how the module was loaded in
memory.".

=== {blank}

"LoadTypeID": "The load type identifies how the module was loaded
in memory.".

=== {blank}

"LoadedModules": "The list of loaded module names.".

=== {blank}

"GeoLocation": "The geographical location usually associated with
an IP address.".

=== {blank}

"LogName": "The name of the database. index. or archive where the
event was logged by the logging system.".

=== {blank}

"LoggedTime": "The time when the logging system collected and logged
the event.</p>This attribute is distinct from the event time in that
event time typically contain the time extracted from the original
event. Most of the time. these two times will be different.".

=== {blank}

"LogonProcess": "The trusted process that validated the authentication
credentials.".

=== {blank}

"LogonType": "The logon type.".

=== {blank}

"LogonTypeID": "The normalized logon type identifier.".

==== {blank}

"Other": "Other logon type.".

==== {blank}

"System": "Used only by the System account. for example at system
startup.".

==== {blank}

"Interactive": "A local logon to device console.".

==== {blank}

"Network": "A user or device logged onto this device from the network.".

==== {blank}

"Batch": "A batch server logon. where processes may be executing on
behalf of a user without their direct intervention.".

==== {blank}

"OSService": "A logon by a service or daemon that was started by the
OS.".

==== {blank}

"Unlock": "A user unlocked the device.".

==== {blank}

"NetworkCleartext": "A user logged on to this device from the network.
The user's password in the authentication package was not hashed.".

==== {blank}

"NewCredentials": "A caller cloned its current token and specified
new credentials for outbound connections. The new logon session has
the same local identity. but uses different credentials for other
network connections.".

==== {blank}

"RemoteInteractive": "A remote logon using Terminal Services or remote
desktop application.".

==== {blank}

"CachedInteractive": "A user logged on to this device with network
credentials that were stored locally on the device and the domain
controller was not contacted to verify the credentials.".

==== {blank}

"CachedRemoteInteractive": "Same as Remote Interactive. This is used
for internal auditing.".

==== {blank}

"CachedUnlock": "Workstation logon.".

=== {blank}

"MACAddress": "The Media Access Control (MAC) address that is associated
with the network interface.".

=== {blank}

"Malware": "The primary malware identified by the event.<p><b>Note:</b>
The primary malware may be the first malware found by the detection
engine. or it may be the most severe malware found.</p>".

=== {blank}

"MD5": "The MD5 checksum of the file content.".

=== {blank}

"Message": "The description of the event.".

=== {blank}

"Metadata": "The metadata associated with the event.".

=== {blank}

"MultiFactorAuthentication": "The Multi Factor Authentication was
used during authentication.".

=== {blank}

"MIMEtype": "The Multipurpose Internet Mail Extensions (MIME) type
of the file. if applicable.".

=== {blank}

"Model": "The peripheral device model.".

=== {blank}

"ModifiedTime": "The time when the object was last modified. See specific
usage.".

=== {blank}

"Modifier": "The user that last modified the object associated with
the event. See specific usage.".

=== {blank}

"Module": "The module that pertains to the event.".

=== {blank}

"Name": "The name of the entity. See specific usage.".

=== {blank}

"Namespace": "The namespace is useful in merger or acquisition situations.
For example. when similar entities exists that you need to keep separate.".

=== {blank}

"NetworkDriver": "The network driver used by the container. For example.
bridge. overlay. host. none. etc.".

=== {blank}

"NetworkInterface": "The network interface that is associated with
the device.".

=== {blank}

"NetworkInterfaces": "The network interfaces that are associated with
the device. one for each MAC address/IP address combination.<p><b>Note:</b>
The first element of the array is the network information that pertains
to the event.</p>".

=== {blank}

"NextRun": "The next run time. See specific usage.".

=== {blank}

"NISTList": "The NIST Cybersecurity Framework recommendations for
managing the cybersecurity risk.".

=== {blank}

"Observables": "The observables associated with the event.".

=== {blank}

"DNSOpcode": "The DNS opcode specifies the type of the query message.".

==== {blank}

"Query": "Standard query".

==== {blank}

"InverseQuery": "Inverse query. obsolete".

==== {blank}

"Status": "Server status request".

==== {blank}

"Reserved": "Reserved. not used".

==== {blank}

"Notify": "Zone change notification".

==== {blank}

"Update": "Dynamic DNS update".

==== {blank}

"DSOMessage": "DNS Stateful Operations (DSO)".

=== {blank}

"OpenMask": "The Windows options needed to open a registry key.".

=== {blank}

"Operation": "Verb/Operation associated with the request".

=== {blank}

"Orchestrator": "The orchestrator managing the container. such as
ECS. EKS. K8s. OpenShift. None.".

=== {blank}

"OrgID": "The unique identifier of the organization to which the user
belongs. For example. Active Directory or AWS Org ID.".

=== {blank}

"OrgUnit": "The name of the organization to which the user belongs.".

=== {blank}

"Origin": "The origin of the event. where the event was created.".

=== {blank}

"OS": "The device operation system.".

=== {blank}

"OtherMalware": "The additional malware that was detected.".

=== {blank}

"Outcome": "The outcome of the event. as defined by the event source.".

=== {blank}

"OutcomeID": "The outcome ID of the event.".

==== {blank}

"Unknown"

==== {blank}

"Other"

=== {blank}

"Owner": "The user that owns the file.".

=== {blank}

"OwnerName": "The name of the service or user account that owns the
resource.".

=== {blank}

"RelatedPackages": "List of vulnerable packages as identified by the
security product".

=== {blank}

"TotalPackets": "The total number of packets (in and out).".

=== {blank}

"PacketsIn": "The number of packets sent from the destination to the
source.".

=== {blank}

"PacketsOut": "The number of packets sent from the source to the destination.".

=== {blank}

"ParentCategories": "An array of parent URL categories.".

=== {blank}

"ParentFolder": "The parent folder in which the file resides. For
example: <code>c:\\windows\\system32</code>".

=== {blank}

"ParentProcess": "The parent process of the <code>actor</code> process.".

=== {blank}

"Path": "The path that pertains to the event or object. See specific
usage.".

=== {blank}

"PeripheralDevice": "The peripheral device that triggered the event.".

=== {blank}

"Permission": "The IAM permission related to an event".

=== {blank}

"PhysicalHeight": "The numeric physical height of display.".

=== {blank}

"PhysicalOrientation": "The numeric physical orientation of display.".

=== {blank}

"PhysicalWidth": "The numeric physical width of display.".

=== {blank}

"ProcessID": "The process identifier. as reported by the operating
system. Process ID (PID) is a number used by the operating system
to uniquely identify an active process.".

=== {blank}

"Port": "The IP port number associated with a connection. See specific
usage.".

=== {blank}

"PostalCode": "The postal code of the location.".

=== {blank}

"Prefix": "The domain prefix.".

=== {blank}

"Priority": "The original priority. as defined by the data source.".

=== {blank}

"PriorityID": "The normalized priority. See specific usage.".

=== {blank}

"Privileges": "The user or group privileges.".

=== {blank}

"PrivilegesRequired": "The level of privileges an attacker must possess
before successfully exploiting the vulnerability.".

=== {blank}

"Process": "The process object.".

=== {blank}

"ProcessedTime": "The event processed time. such as an ETL operation.".

=== {blank}

"Product": "The product that reported the event.".

=== {blank}

"ProductIdentifier": "Unique Identifier of a product.".

=== {blank}

"Profiles": "The list of profiles used to create the event.".

=== {blank}

"ProjectID": "Cloud project identifier.".

=== {blank}

"ProtocolName": "The TCP/IP protocol name in lowercase. as defined
by the Internet Assigned Numbers Authority (IANA). See <a target='_blank'
href='https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml'>Protocol Numbers</a>. For example: <code>tcp</code> or <code>udp</code>.".

=== {blank}

"ProtocolNumber": "The TCP/IP protocol number. as defined by the Internet
Assigned Numbers Authority (IANA). Use -1 if the protocol is not defined
by IANA. See <a target='_blank' href='https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml'>Protocol Numbers</a>. For example: <code>6</code> for TCP and <code>17</code> for UDP.".

=== {blank}

"ProtocolVersion": "The Protocol version.".

=== {blank}

"ProtocolVersionID": "The Protocol version identifier.".

=== {blank}

"Provider": "The origin of information associated with the event.
See specific usage.".

=== {blank}

"Proxy": "If a proxy connection is present. the connection from the
client to the proxy server.".

=== {blank}

"PublicIP": "The public IP address.<p><b>Note:</b> The <b>Device Public
IP</b> is populated with the value of the <i>x-forwarded-for</i> message
header. if present.</p>.".

=== {blank}

"QuarantineUID": "The unique identifier of the item that was quarantined
or restored from quarantine.".

=== {blank}

"DNSQuery": "The Domain Name System (DNS) query.".

=== {blank}

"HTTPQueryString": "The query portion of the URL. For example: the
query portion of the URL <code>http://www.example.com/search?q=bad&sort=date</code> is <code>q=bad&sort=date</code>.".

=== {blank}

"QueryTime": "The Domain Name System (DNS) query time.".

=== {blank}

"RawData": "The event data as received from the event source.".

=== {blank}

"ResponseCode": "The DNS server response code. See <a target='_blank'
href='https://datatracker.ietf.org/doc/html/rfc6895'>RFC-6895</a>.".

=== {blank}

"ResponseCodeID": "The DNS server response code id. See <a target='_blank'
href='https://datatracker.ietf.org/doc/html/rfc6895'>RFC-6895</a>.".

==== {blank}

"Other": "The dns response code is not defined by the RFC.".

==== {blank}

"NoError": "No Error.".

==== {blank}

"FormError": "Format Error.".

==== {blank}

"ServError": "Server Failure.".

==== {blank}

"NXDomain": "Non-Existent Domain.".

==== {blank}

"NotImp": "Not Implemented.".

==== {blank}

"Refused": "Query Refused.".

==== {blank}

"YXDomain": "Name Exists when it should not.".

==== {blank}

"YXRRSet": "RR Set Exists when it should not.".

==== {blank}

"NXRRSet": "RR Set that should exist does not.".

==== {blank}

"NotAuth": "Not Authorized or Server Not Authoritative for zone.".

==== {blank}

"NotZone": "Name not contained in zone.".

==== {blank}

"DSOTYPENI": "DSO-TYPE Not Implemented.".

==== {blank}

"BADSIG_VERS": "TSIG Signature Failure or Bad OPT Version.".

==== {blank}

"BADKEY": "Key not recognized.".

==== {blank}

"BADTIME": "Signature out of time window.".

==== {blank}

"BADMODE": "Bad TKEY Mode.".

==== {blank}

"BADNAME": "Duplicate key name.".

==== {blank}

"BADALG": "Algorithm not supported.".

==== {blank}

"BADTRUNC": "Bad Truncation.".

==== {blank}

"BADCOOKIE": "Bad/missing Server Cookie.".

==== {blank}

"Unassigned": "The codes deemed to be unassigned by the RFC (unassigned
codes: 12-15. 24-3840. 4096-65534).".

==== {blank}

"Reserved": "The codes deemed to be reserved by the RFC (codes: 3841-4095.
65535).".

=== {blank}

"DNSRData": "The data describing the DNS resource. The meaning of
this data depends on the type and class of the resource record.".

=== {blank}

"ReferenceEventCode": "The event code/ID. as defined by the event
source. It is used to identify the type of event. For example. the
Windows event Code or ID.".

=== {blank}

"ReferenceEventName": "The event name. as defined by the event source.".

=== {blank}

"ReferenceEventID": "The event instance identifier. as defined by
the event source. It is the index of the event in an external event
log. For example. the Windows EventRecordID.".

=== {blank}

"OriginalTime": "The original event time as reported by the event
source.".

=== {blank}

"ReferenceUID": "The reference to a unique identifier. managed by
an external system.".

=== {blank}

"References": "Supporting reference URLs".

=== {blank}

"HTTPReferrer": "The request header that identifies the address of
the previous web page. which is linked to the current web page or
resource being requested.".

=== {blank}

"RegistryKey": "The registry key.".

=== {blank}

"RegistryKeyResult": "The result of the registry key change. It should
contain the new values of the changed attributes.".

=== {blank}

"RegistryValue": "The registry value.".

=== {blank}

"RegistryValueResult": "The result of the registry value change. It
should contain the new values of the changed attributes.".

=== {blank}

"Region": "The name or the code of a region. See specific usage.".

=== {blank}

"RelatedFindings": "Describes findings related to a finding as identified
by the security product.".

=== {blank}

"RelatedVulnerabilities": "List of vulnerabilities that are related
to this vulnerability.".

=== {blank}

"Relay": "The network relay that is associated with the event.".

=== {blank}

"RemediationDetails": "The Remediation object describes details about
recommended remediation strategies.".

=== {blank}

"RemoteDisplay": "The remote display affiliated with the event".

=== {blank}

"ReputationScore": "The original reputation score as reported by the
event source.".

=== {blank}

"ReputationScoreID": "The normalized reputation score identifier.".

==== {blank}

"Other": "The reputation score is not mapped. See the <code>rep_score</code>
attribute. which contains a data source specific value.".

==== {blank}

"Unknown": "The reputation score is unknown.".

==== {blank}

"VerySafe": "Long history of good behavior.".

==== {blank}

"Safe": "Consistently good behavior.".

==== {blank}

"ProbablySafe": "Reasonable history of good behavior.".

==== {blank}

"LeansSafe": "Starting to establish a history of normal behavior.".

==== {blank}

"MaynotbeSafe": "No established history of normal behavior.".

==== {blank}

"ExerciseCaution": "Starting to establish a history of suspicious
or risky behavior.".

==== {blank}

"PossiblyMalicious": "Strong possibility of maliciousness.".

==== {blank}

"ProbablyMalicious": "Indicators of maliciousness.".

==== {blank}

"Malicious": "Proven evidence of maliciousness.".

=== {blank}

"APIRequestDetails": "General Purpose API Request Object. See specific
usage".

=== {blank}

"RequestedPermissions": "The permissions mask that were requested
by the process.".

=== {blank}

"Requirements": "A list of applicable compliance requirements for
which this finding is related to.".

=== {blank}

"IPAddress": "The resolved IP address. in either IPv4 or IPv6 format.
For example. Layer 4 load balancer translated IP address.".

=== {blank}

"Resource": "The target resource.".

=== {blank}

"ResourcesArray": "A list of resources associated to an event.".

=== {blank}

"ResourceType": "The context in which a resource was retrieved in
a web request.".

=== {blank}

"ResourceID": "The unique identifier of a cloud resource. For example.
S3 Bucket name. EC2 Instance Id.".

=== {blank}

"APIResponseDetails": "General Purpose API Response Object. See specific
usage.".

=== {blank}

"ResponseTime": "The Domain Name System (DNS) response time.".

=== {blank}

"Risk": "The Common Vulnerability Scoring System (CVSS) calculated
risk.".

=== {blank}

"RiskLevel": "The normalized risk level.".

=== {blank}

"RiskLevelID": "The normalized risk level id.".

==== {blank}

"Info"

==== {blank}

"Low"

==== {blank}

"Medium"

==== {blank}

"High"

==== {blank}

"Critical"

=== {blank}

"RiskScore": "The original risk score as reported by the event source.".

=== {blank}

"Rule": "The rules that reported the events.".

=== {blank}

"Run-AsUser": "The user account the process is running as.".

=== {blank}

"RunState": "The state of the job or service. See specific usage.".

=== {blank}

"RunStateID": "The state of the job or service. See specific usage.".

=== {blank}

"Runtime": "The runtime managing this container.".

=== {blank}

"SameSite": "The cookie attribute that lets servers specify whether/when
cookies are sent with cross-site requests. Values are: Strict. Lax
or None".

=== {blank}

"Sandbox": "The name of the containment jail (i.e.. sandbox). For
example. hardened_ps. high_security_ps. oracle_ps. netsvcs_ps. or
default_ps.".

=== {blank}

"ScaleFactor": "The numeric scale factor of display.".

=== {blank}

"Scheme": "The scheme portion of the URL. For example: <code>http</code>.
<code>https</code>. <code>ftp</code>. or <code>sftp</code>.".

=== {blank}

"Secure": "The cookie attribute to only send cookies to the server
with an encrypted request over the HTTPS protocol.".

=== {blank}

"SecurityDescriptor": "The object security descriptor.".

=== {blank}

"SequenceNumber": "Sequence number of the event. The sequence number
is a value available in some events. to make the exact ordering of
events unambiguous. regardless of the event time precision.".

=== {blank}

"SerialNumber": "The serial number that pertains to the object. See
specific usage.".

=== {blank}

"SignatureSerialNumber": "The object serial number.".

=== {blank}

"ServerCipherSuites": "The server cipher suites that were exchanged
during the TLS handshake negotiation.".

=== {blank}

"Service": "The cloud service that pertains to the event.".

=== {blank}

"Session": "The session information.".

=== {blank}

"SessionUID": "The unique ID of the user session. as reported by the
OS.".

=== {blank}

"Severity": "The original event severity. as defined by the event
source.</p>The severity is a measurement the effort and expense required
to manage and resolve an event or incident.".

=== {blank}

"SeverityID": "The normalized event severity.</p>The normalized severity
is a measurement the effort and expense required to manage and resolve
an event or incident. Smaller numerical values represent lower impact
events. and larger numerical values represent higher impact events.".

==== {blank}

"Other": "The event severity is not mapped. See the <code>severity</code>
attribute. which contains a data source specific value.".

==== {blank}

"Unknown": "The event severity is not known.".

==== {blank}

"Informational": "Informational message. No action required.".

==== {blank}

"Low": "The user decides if action is needed.".

==== {blank}

"Medium": "Action is required but the situation is not serious at
this time.".

==== {blank}

"High": "Action is required immediately.".

==== {blank}

"Critical": "Action is required immediately and the scope is broad.".

==== {blank}

"Fatal": "An error occurred but it is too late to take remedial action.".

=== {blank}

"SHA-1": "The SHA-1 checksum of the file content.".

=== {blank}

"SHA-256": "The SHA-256 checksum of the file content.".

=== {blank}

"Shell": "The user's login shell.".

=== {blank}

"DigitalSignature": "The digital signature of the file.".

=== {blank}

"Size": "The size of data. in bytes.".

=== {blank}

"OSServicePack": "The name of the latest Service Pack.".

=== {blank}

"OSServicePackVersion": "The version number of the latest Service
Pack.".

=== {blank}

"SourceEndpoint": "The network source endpoint.".

=== {blank}

"SourceURL": "The URL pointing towards the source of an entity. See
specific usage.".

=== {blank}

"SourceUser": "The existing user from which an activity was initiated.".

=== {blank}

"StartTime": "The start time of a time period. See specific usage.".

=== {blank}

"State": "The state of the event or object. as defined by the event
source. See specific usage.".

=== {blank}

"StateID": "The state ID of the event or object. See specific usage.".

=== {blank}

"Status": "The event status. as reported by the event source.".

=== {blank}

"StatusDetails": "The status details contains additional information
about the event outcome.".

=== {blank}

"StatusID": "The cross-platform normalized status of the activity
or alert reported by the event.".

==== {blank}

"Other": "The event status is not mapped. See the <code>status</code>
attribute. which contains a data source specific value.".

==== {blank}

"Unknown"

==== {blank}

"Success"

==== {blank}

"Failure"

=== {blank}

"Subnet": "The subnet mask.".

=== {blank}

"SubnetUID": "The unique identifier of a virtual subnet.".

=== {blank}

"SupportingData": "Additional data supporting a finding as provided
by security tool".

=== {blank}

"ServiceName": "The service name in service-to-service connections.
For example. AWS VPC logs the pkt-src-aws-service and pkt-dst-aws-service
fields identify the connection is coming from or going to an AWS service.".

=== {blank}

"SystemCall": "The system call that was invoked.".

=== {blank}

"Tactics": "The a list of tactic ID's that are associated with the
attack technique. as defined by <a target='_blank' href='https://attack.mitre.org/wiki/ATT&CK_Matrix'>ATT&CK Matrix<sup>TM</sup></a>.".

=== {blank}

"ImageTag": "The image tag. For example: <code>1.11-alpine</code>.".

=== {blank}

"TCPFlags": "The network connection TCP header flags (i.e.. control
bits).".

=== {blank}

"TechniqueName": "The name of the attack technique. as defined by
<a target='_blank' href='https://attack.mitre.org/wiki/ATT&CK_Matrix'>ATT&CK
Matrix<sup>TM</sup></a>. For example: <code>Drive-by Compromise</code>.".

=== {blank}

"TechniqueID": "The unique identifier of the attack technique. as
defined by
<a target='_blank' href='https://attack.mitre.org/wiki/ATT&CK_Matrix'>ATT&CK
Matrix<sup>TM</sup></a>. For example: <code>T1189</code>.".

=== {blank}

"TerminationTime": "The time that the entity was terminated. See specific
usage.".

=== {blank}

"URLText": "The URL. For example: <code>http://www.example.com/download/trouble.exe</code>.".

=== {blank}

"ThreadID": "The Identifier of the thread associated with the event.
as returned by the operating system.".

=== {blank}

"EventTime": "The normalized event occurrence time <p><b>Note:</b>
The format is yet undecided".

=== {blank}

"TimeZone": "The number of minutes that the reported event <code>time</code>
is ahead or behind UTC. A number in the range -1.080 to +1.080.".

=== {blank}

"Title": "The title of an entity. See specific usage.".

=== {blank}

"TLS": "The Transport Layer Security (TLS) attributes.".

=== {blank}

"Traffic": "The network traffic refers to the amount of data moving
across a network at a given point of time. Intended to be used alongside
Network Connection.".

=== {blank}

"TrafficPath": "The boundary of the connection. For cloud connections.
this translates to the traffic-path (same VPC. through IGW. etc.).
For traditional networks. this is described as Local. Internal. or
External.".

=== {blank}

"TrafficPathID": "The boundary of the connection. For cloud connections.
this translates to the traffic-path (same VPC. through IGW. etc.).
For traditional networks. this is described as Local. Internal. or
External.".

==== {blank}

"Unknown"

==== {blank}

"Local": "Local network traffic on the same endpoint.".

==== {blank}

"Internal": "Internal network traffic between two endpoints inside
network.".

==== {blank}

"External": "External network traffic between two endpoints on the
Internet or outside the network.".

==== {blank}

"SameVPC": "Through another resource in the same VPC".

==== {blank}

"Internet/VPCGateway": "Through an Internet gateway or a gateway VPC
endpoint".

==== {blank}

"VirtualPrivateGateway": "Through a virtual private gateway".

==== {blank}

"Intra-regionVPC": "Through an intra-region VPC peering connection".

==== {blank}

"Inter-regionVPC": "Through an inter-region VPC peering connection".

==== {blank}

"LocalGateway": "Through a local gateway".

==== {blank}

"GatewayVPC": "Through a gateway VPC endpoint (Nitro-based instances
only)".

==== {blank}

"InternetGateway": "Through an Internet gateway (Nitro-based instances
only)".

=== {blank}

"TransactionUID": "The unique identifier of the transaction.".

=== {blank}

"TTL": "The time interval that the resource record may be cached.
Zero value means that the resource record can only be used for the
transaction in progress. and should not be cached.".

=== {blank}

"Type": "The type of an object or value. See specific usage.".

=== {blank}

"TypeID": "The type identifier of an object. See specific usage.".

==== {blank}

"Other": "The type is not mapped. See the <code>type</code> attribute.
which may contain a data source specific value.".

==== {blank}

"Unknown": "The type is unknown.".

=== {blank}

"Types"

=== {blank}

"UniqueID": "The unique identifier. See specific usage.".

=== {blank}

"UnmappedData": "The attributes that are not mapped to the event schema.
The names and values of those attributes are specific to the event
source.".

=== {blank}

"UpdateTime": "A Timestamp indicating when an entity was last updated.".

=== {blank}

"URL": "The URL object that pertains to the event or object. See specific
usage.".

=== {blank}

"User": "The user that pertains to the event or object.".

=== {blank}

"HTTPUser-Agent": "The request header that identifies the operating
system and web browser.".

=== {blank}

"UserInteraction": "The requirement for a user. other than the attacker.
to participate in the successful compromise of the vulnerable component.".

=== {blank}

"UserResult": "The result of the user account change. It should contain
the new values of the changed attributes.".

=== {blank}

"UUID": "The universally unique identifier. See specific usage.".

=== {blank}

"Value": "The value that pertains to the object. See specific usage.".

=== {blank}

"Vendor": "The vendor that pertains to the object. See specific usage.".

=== {blank}

"Version": "The version that pertains to the event or object. See
specific usage.".

=== {blank}

"VLAN": "The Virtual LAN identifier.".

=== {blank}

"VPCUID": "The unique identifier of the Virtual Private Cloud (VPC).".

=== {blank}

"Vulnerability": "The vulnerability object describes details related
to the observed vulnerability".

=== {blank}

"X-Forwarded-For": "The X-Forwarded-For header identifying the originating
IP address(es) of a client connecting to a web server through an HTTP
proxy or a load balancer.".

=== {blank}

"ExtendedAttributes": "An unordered collection of zero or more name/value
pairs where each pair represents a file or folder extended attribute.</p>For
example: Windows alternate data stream attributes (ADS stream name.
ADS size. etc.). user-defined or application-defined attributes. ACL.
owner. primary group. etc. Examples from DCS: </p><ul><li><strong>ads_name</strong></li><li><strong>ads_size</strong></li><li><strong>dacl</strong></li><li><strong>owner</strong></li><li><strong>primary_group</strong></li><li><strong>link_name</strong> - name of the link associated to the file.</li><li><strong>hard_link_count</strong> - the number of links that are associated to the file.</li></ul>".

=== {blank}

"NetworkZone": "The network zone or LAN segment.".
