name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref_name }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: metanorma/metanorma:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Metanorma cache
        uses: actions-mn/cache@v1

      - name: Metanorma generate site
        uses: actions-mn/site-gen@v1
        with:
          agree-to-terms: true

      - name: Upload metanorma artifact
        uses: actions/upload-artifact@v3
        with:
          name: draft
          path: site
